language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
script: 
  - npm run test:coveralls
deploy:
  provider: npm
  skip-cleanup: true
  email: "$AUTH_EMAIL"
  api_key: "$AUTH_TOKEN"
  on:
    tags: true
    node: 10
