language: node_js
node_js:
  - "8"
  - "9"
  - "10"
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
script: 
  - npm run test:coveralls
deploy:
    provider: npm
    email: "$AUTH_EMAIL"
    api_key: "$AUTH_TOKEN"
